### ISSUE TITLE
Problematic writes

### ISSUE THREAD

**Issue by arj03** [ssb-ngi-pointer/jitdb#185]
Saving a core index is done [async](https://github.com/ssb-ngi-pointer/jitdb/blob/41a1b326a682b8c9a18f9b7dd7283021d31cc428/index.js#L176). This means we could end up in a situation where an index is written before things like `seq.index`, which could lead to [bad things](https://github.com/ssb-ngi-pointer/jitdb/blob/41a1b326a682b8c9a18f9b7dd7283021d31cc428/index.js#L478) if it crashes or was forced to terminate in that particular point in time.

**Comment by staltz** [comment]
True! Good that you found this, I had no suspicions about that part. Do you have a fix in mind already? Like, we could add callbacks on the saving core indexes, and when they are done, we save the non-core index. But we also have to be careful with the Nth saving of index A to wait for the `N-1`th saving of A.

**Comment by staltz** [comment]
If `seq.index` is broken, could that affect the leveldb bug directly? Because `keys` index is based on the `seq()` operator.

For instance:

Suppose `type_post.index` was saved but `seq.index` wasn't saved, as you originally described.

Like (each uppercase letters is a record):

```
      seq.index: A B C D E F G
type_post.index: A B C D E F G H I J K
```

Then, supposed JITDB could update the `type_post.index` in [update index](https://github.com/ssb-ngi-pointer/jitdb/blob/41a1b326a682b8c9a18f9b7dd7283021d31cc428/index.js#L517).

The [startSeq](https://github.com/ssb-ngi-pointer/jitdb/blob/41a1b326a682b8c9a18f9b7dd7283021d31cc428/index.js#L493) would be **H** (because the `for` loop would never find the common `offset` value between `seq.index` and `type_post.index` and would just run through the whole for loop), but the `gt` to [start the stream](https://github.com/ssb-ngi-pointer/jitdb/blob/41a1b326a682b8c9a18f9b7dd7283021d31cc428/index.js#L517) would be **K**, because `gt` is just the offset of the `type_post.index`.

Then, when the stream write happens, we get record **L** and we [update seq index](https://github.com/ssb-ngi-pointer/jitdb/blob/41a1b326a682b8c9a18f9b7dd7283021d31cc428/index.js#L523) to so that **H's seq would point to L's offset**. That's clearly the wrong offset.

Then, when `keys` index uses the `seq()` operator, it just asks JITDB to resolve the **H's seq to an offset**, giving L's offset, and then from that offset, fetch the record in the log. So `keys` index ends up giving L's SSB key instead of H. In other words, the msg keys are **ahead** of what they should be, which is the symptom we're seeing in https://github.com/ssb-ngi-pointer/ssb-db2/issues/291, correct?

I think that's it, but please double check it.

**Comment by arj03** [comment]
Sadly I don't think that is the cause of the level bug. Both base and keys index are off-by-2 in Daves example and his seq is ok. Furthermore level indexes should not use jitdb, they have their own [`offset`](https://github.com/ssb-ngi-pointer/ssb-db2/blob/dd88a14d798c55fb200d7e401029d8a4bf87615c/db.js#L502).
