### ISSUE TITLE
`batch` operator is not batching

### ISSUE THREAD

**Issue by nichoth** [ssb-ngi-pointer/jitdb#187]
I expect the batch to be in a size of ten, but it returns the full log instead. Am I doing something wrong in the test case?

https://github.com/planetary-social/viewer/blob/943763cece328e1c1904f0002edfbb1ddf239f9d/index.js#L80

**Comment by arj03** [comment]
Seems like you are calling `collect` which gives you everything

**Comment by nichoth** [comment]
Interesting, I would expect the `batch` operator to not be affected by the pull stream pipeline, and in the example would just return a stream of 10 items.

**Comment by staltz** [comment]
`batch()` helps create a pull-stream source (see `toPullStream()`), but **after** `toPullStream()` what matters is the pull-stream operators you use, and in this case you used `collect()` which puts all stream items (up until the stream "end") in one single array.

You could have used `pull.take(10), pull.collect()` and dropped the `batch()`. I don't think there is any problem with `batch()`, the docs say that it causes the pull-stream source to deliver msgs one at a time.

Preliminarily closing this since it seems like a pull-stream question, not a jitdb issue
